version: "3.8"

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql-go
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=1
      - POSTGRESQL_DATABASE=email_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/bitnami/postgresql
    networks:
      - email-service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - email-service

volumes:
  pgdata:
  kafka_data:

networks:
  email-service:
