services:
  postgresql:
    image: "bitnami/postgresql:latest"
    container_name: postgresql-go
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=1
      - POSTGRESQL_DATABASE=email_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/bitnami/postgresql
    networks:
      - email-service

volumes:
  pgdata:

networks:
  email-service:
